blogOkladnikova/Models/ErrorViewModel.cs
using System;

namespace blogOkladnikova.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

blogOkladnikova/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace blogOkladnikova.Controllers
{
    /// <summary>
    /// Controller to communicate with the view Blog
    /// </summary>

    public class BlogController : Controller
    {
        /// <summary>
        /// Method for returning a view Blog->Index
        /// </summary>
        public IActionResult Index()
        {
            return View();
        }
    }
}

blogOkladnikova/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using blogOkladnikova.Models;
using Microsoft.Extensions.Options;
using blogOkladnikova.Options;

namespace blogOkladnikova.Controllers
{
    /// <summary>
    /// Controller to communicate with the views Home
    /// </summary>

    public class HomeController : Controller
    {
        
        private readonly ILogger<HomeController> _logger;
        private readonly IOptions<ServerInformation> _serverinformation;

        /// <summary>
        /// Constructer for class HomeController <see cref="HomeController"/>
        /// </summary>
        /// ILogger service used for logging is passed
        /// IOptions service used to implement the server side
        public HomeController(ILogger<HomeController> logger, IOptions<ServerInformation> serverinformation)  
        {
            _logger = logger;
            _serverinformation = serverinformation;
        }

        /// <summary>
        /// Method for returning a view Home->Index
        /// </summary>

        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Method for returning a view Home->Privacy
        /// </summary>

        public IActionResult Privacy()
        {
            return View();
        }
        /// <summary>
        /// Method for returning error Models->ErrorViewModels
        /// </summary>
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        
    }
}

blogOkladnikova/Views/Blog/Index.cshtml
@{
    ViewData["Title"] = "BlogIndex";
}

<head>

</head>
<body>
    <h1>Hello</h1>
</body>

blogOkladnikova/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "MyBlog";
}

<head>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Peddana&family=Zilla+Slab:ital,wght@1,300&display=swap" rel="stylesheet">
</head>
<body>

</body>
<div class="text-center">
    <h1 class="display-4">Welcome to Hathaway Blog</h1>
   
    <div class="head_blog">
        <img src="images/i.jpg" alt="">
        <p>Blog about what I like. With different nice content.</p>
    </div>
    
</div>

blogOkladnikova/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - blogOkladnikova</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">blogOkladnikova</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Index">Blog</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - blogOkladnikova - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>